version: "2.1"
services:
  resilio-sync:
    image: lscr.io/linuxserver/resilio-sync:latest
    container_name: resilio-sync
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - ./config:/config
      - ./downloads:/downloads
      - ./data:/sync
    ports:
      - 8888:8888
      - 55555:55555
    restart: unless-stopped
