version: '2'
services:
  mariadb:
    image: docker.io/bitnami/mariadb:10.6
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=no
      - MARIADB_USER=bn_drupal
      - MARIADB_DATABASE=bitnami_drupal
      - MARIADB_PASSWORD=${GEN_PASS}
      - MARIADB_ROOT_PASSWORD=${GEN_PASS2}
    volumes:
      - 'mariadb_data:/bitnami/mariadb'
  drupal:
    image: docker.io/bitnami/drupal:9
    ports:
      - '88:8080'
      - '473:8443'
    environment:
      - DRUPAL_DATABASE_HOST=${LAN_IP}:88
      - DRUPAL_DATABASE_HOST=mariadb
      - DRUPAL_DATABASE_PORT_NUMBER=3306
      - DRUPAL_DATABASE_USER=bn_drupal
      - DRUPAL_DATABASE_NAME=bitnami_drupal
      - DRUPAL_DATABASE_PASSWORD=${GEN_PASS}
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=no
    volumes:
      - 'drupal_data:/bitnami/drupal'
    depends_on:
      - mariadb
volumes:
  mariadb_data:
    driver: local
  drupal_data:
    driver: local
