version: "3.8"
services:
  invidious:
    image: quay.io/invidious/invidious:latest
    restart: always
    stop_grace_period: 3s
    ports:
      - ${LAN_IP}:82:3000
    environment:
      INVIDIOUS_CONFIG: |
        db:
          dbname: invidious
          user: invidious
          password: ${GEN_PASS}
          host: postgres
          port: 5432
        check_tables: true
        popular_enabled: false
        login_enabled: false
        statistics_enabled: false
        hsts: false
        https_only: false
        external_port: 442
        domain: ${LAN_IP}
    healthcheck:
      test: wget -nv --tries=1 --spider http://${LAN_IP}:82/api/v1/comments/jNQXAC9IVRw || exit 1
      interval: 30s
      timeout: 5s
      retries: 2
    depends_on:
      - postgres

  postgres:
    image: postgres:14
    restart: always
    # purposefully excluded volumes section
    # the database will reset on recreate
    environment:
      POSTGRES_DB: invidious
      POSTGRES_USER: invidious
      POSTGRES_PASSWORD: ${GEN_PASS}
    healthcheck:
      test: pg_isready -U invidious -d invidious
      interval: 10s
      timeout: 5s
      retries: 5
